# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GoForCare - Health Beyond Borders
email: contact@goforcare.co
description: > # this means to ignore newlines until "baseurl:"
  At Go For Care we make health services available and affordable for patients from all over the world.
  We provide them the opportunity to receive a variety of treatments they couldn't find or afford at their home countries, while they enjoy of the magnificent beauty of Colombia and our people.
  We will be next to you, from beginning to end in this journey you are going to take.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goforcare.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: default
      lang: fr